Accordion in edit group block
eea/volto-accordion-block pull request #1
Opened 2020-11-04 11:11 UTC by nileshgulia1

2020-11-04 12:13 UTC, tiberiuichim requested changes

2020-11-04 12:13 UTC, tiberiuichim commented on src/components/manage/Blocks/Accordion/Edit.jsx
> +        onChange={(initialData) => {
why is onChange needed here?

2020-11-04 12:14 UTC, nileshgulia1 commented on src/components/manage/Blocks/Accordion/Edit.jsx
> +        onChange={(initialData) => {
Ah, its no need. I'll remove it.

2020-11-04 12:18 UTC, nileshgulia1 commented
@tiberiuichim Should we also allow editors to add more accordion(s) from the sideBar like in the columns block?

2020-11-04 15:06 UTC, tiberiuichim requested changes
What about "data" for the AccordionEdit ?

2020-11-04 18:12 UTC, nileshgulia1 commented
@tiberiuichim I have made some styling changes along with changed you requested. Please review again.

2020-11-04 19:34 UTC, tiberiuichim commented
@nileshgulia1 will it have the content have the same padding in view mode? We try to keep the views as much "WYSIWYG", so that there's not a lot of differences in text wrapping.

2020-11-05 07:57 UTC, nileshgulia1 commented
@tiberiuichim Yes, I Think content layout in both Edit and View should not have differences. I also added Accordion in View.

2020-11-09 11:30 UTC, nileshgulia1 commented
@tiberiuichim Would you mind please giving it another shot..?

2020-11-09 20:37 UTC, merged