Updated I18n support and Spanish translation
eea/volto-accordion-block pull request #64
Opened 2023-05-15 19:48 UTC by macagua

2023-05-16 06:14 UTC, nileshgulia1 approved these changes

2023-05-17 21:01 UTC, macagua commented
@nileshgulia1 :-)

2023-05-17 21:01 UTC, macagua commented
@avoinea please can you check this "pull request" and if all ok merge it? thanks

2023-06-07 14:51 UTC, avoinea requested changes

2023-06-18 05:24 UTC, macagua commented on src/components/manage/Blocks/Accordion/LayoutSchema.js
> +  title: intl.formatMessage(messages.AccordionBlockSettings),
@avoinea I am sorry for the delay, please can you check again this "pull request" and if all ok merge it? thanks

2023-06-20 13:09 UTC, avoinea commented
@macagua How do you test your changes? Did you start Volto with this branch?!

```
/opt/sandbox/clean-volto-project/node_modules/react/cjs/react.development.js:1476
      throw Error( "Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:\n1. You might have mismatching versions of React and the renderer (such as React DOM)\n2. You might be breaking the Rules of Hooks\n3. You might have more than one copy of React in the same app\nSee https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem." );
            ^

Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

  49 |
  50 | const applyConfig = (config) => {
> 51 |   const intl = useIntl();
  52 |   config.blocks.blocksConfig.accordion = {
  53 |     id: 'accordion',
  54 |     title: intl.formatMessage(messages.Accordion),

    at resolveDispatcher (/opt/sandbox/clean-volto-project/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (/opt/sandbox/clean-volto-project/node_modules/react/cjs/react.development.js:1484:20)
    at useIntl (/opt/sandbox/clean-volto-project/node_modules/react-intl/dist/components/useIntl.js:7:24)
    at applyConfig (/opt/sandbox/clean-volto-project/src/addons/volto-accordion-block/src/index.js:51:1)
    at /opt/sandbox/clean-volto-project/build/webpack:/tmp/tmp-218169-r8Vo36tiOEyv-.js:16:1
    at /opt/sandbox/clean-volto-project/build/webpack:/tmp/tmp-218169-r8Vo36tiOEyv-.js:34:1
    at Array.reduce (<anonymous>)
    at load (/opt/sandbox/clean-volto-project/build/webpack:/tmp/tmp-218169-r8Vo36tiOEyv-.js:34:1)
    at Module../node_modules/@plone/volto/src/config/index.js (/opt/sandbox/clean-volto-project/build/webpack:/node_modules/@plone/volto/src/config/index.js:224:1)
    at __webpack_require__ (/opt/sandbox/clean-volto-project/build/webpack:/webpack/bootstrap:754:1)

sswp> !!! Script exited with code 1
```

2023-06-21 05:36 UTC, nileshgulia1 commented on src/index.js
> +  choices.push(['accordion', intl.formatMessage(messages.Accordion)]);
I suppose how jenkins passes then? 🤔

2023-08-24 09:07 UTC, ichim-david commented
@macagua if you can update your fork with the latest changes from devel we can proceed with trying to merge the changes.

2023-08-25 02:54 UTC, macagua commented
@avoinea @ichim-david I fixed all errors, I tested this addon following the DEVELOP file and updated this branch, I hope this this pull request pass all the test checkout.

2023-08-25 02:56 UTC, macagua commented on src/components/manage/Blocks/Accordion/Schema.js
> +  title: intl.formatMessage(messages.Accordion),
Done with commit [4281bab]

2023-08-25 02:57 UTC, macagua commented on src/index.js
> +  choices.push(['accordion', intl.formatMessage(messages.Accordion)]);
Done with commit [4281bab]

2023-08-25 02:57 UTC, macagua commented on src/components/manage/Blocks/Accordion/LayoutSchema.js
> +  title: intl.formatMessage(messages.AccordionBlockSettings),
Done with commit [4281bab]

2023-08-25 05:48 UTC, avoinea commented
@macagua Thank you! 

As I am on vacation this week I will ask someone from EDW to look into your PRs. Otherwise I can take a look next week: 😉

2023-08-25 09:49 UTC, ichim-david commented
@macagua  have a look at the pull request that I've opened by making a local pull request with the changes from your fork, I will continue with writing there

2023-08-25 10:07 UTC, macagua commented
@avoinea enjoy your vacation 
@ichim-david ok any news, just tell me...

2023-08-25 18:07 UTC, ichim-david commented
@macagua  I'm going to close this pull request as I took your commits and made a local branch
where I also had to make some commits in order to get the build to pass.
https://github.com/eea/volto-accordion-block/pull/91
Next week we will also make a release of these changes, thank you for your contribution!

2023-08-25 18:07 UTC, closed without merging

2023-08-25 19:43 UTC, macagua commented
@ichim-david Thanks your time and advices to help me for make done it. I learned mucho!