css fixes for block chooser and power user menu
eea/volto-accordion-block pull request #76
Opened 2023-07-12 14:21 UTC by claudiaifrim

2023-07-12 15:00 UTC, ichim-david requested changes
@claudiaifrim please bump up the package version to at least 9.1.0 as it's not a point release.
Also since this addon is used by the general community test these changes on a fresh version of Volto 16 and 17

2023-07-13 08:15 UTC, claudiaifrim commented
> @claudiaifrim please bump up package version to at least 9.1.0 as it's not a point release. Also since this adoon is used by the general community test these changes on a fresh version of Volto 16 and 17

Done!
@ichim-david, I tested the changes (develop branch) on basic projects - default volto blocks + volto-accordion-block and works as expected.

Tested with:
* Volto version: 16.21.3 (browsers: Chrome, Firefox, Safari)
* Volto version: 17.0.0-alpha.17 (browsers: Chrome, Firefox, Safari)

2023-07-13 13:15 UTC, ichim-david approved these changes

2023-07-13 13:47 UTC, razvanMiu approved these changes

2023-07-13 15:43 UTC, merged